services:
  web:
    build: .
    # ports:
    #   - "8080:8080"
    env_file:
      - .env
    # depends_on:
    #   - whatsapp
    networks:
      - aidea-space-v3

  # whatsapp:
  #   build:
  #     context: ./whatsapp-server
  #     dockerfile: Dockerfile
  #   # ports:
  #   #   - "3182:3182"
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   networks:
  #     - aidea-space-v3

networks:
  aidea-space-v3:
    driver: bridge
